// This file is auto-generated by syncFoundry.ts. Do not edit directly.
import { getAbiItem, Abi } from 'viem'
type Deployments = { [key: string]: { [key: string]: string } };
type ABIKP = { [key: string]: Abi };

export const deployments: Deployments = {
  "Will": {
    "11155420": "0x2a1EeaF390C6F4274F59A20224a2841a469d9d68"
  },
  "Membranes": {
    "11155420": "0x8257540c2f41605fb70DCfCbA70C48F8420840CF"
  },
  "Execution": {
    "11155420": "0x15364dDE1B4C87F8CE3539e3e59A65fbCed12207"
  },
  "WillWe": {
    "11155420": "0x41A717c4d277c26e08C46ec6c8d26553F067A769"
  }
};

export const ABIs: ABIKP = {
  "Will": [
    {
      "type": "constructor",
      "inputs": [
        {
          "name": "initMintAddrs_",
          "type": "address[]",
          "internalType": "address[]"
        },
        {
          "name": "initMintAmts_",
          "type": "uint256[]",
          "internalType": "uint256[]"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "receive",
      "stateMutability": "payable"
    },
    {
      "type": "function",
      "name": "DOMAIN_SEPARATOR",
      "inputs": [],
      "outputs": [
        {
          "name": "result",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "allowance",
      "inputs": [
        {
          "name": "owner",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "spender",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "result",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "approve",
      "inputs": [
        {
          "name": "spender",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "amount",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "balanceOf",
      "inputs": [
        {
          "name": "owner",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "result",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "burn",
      "inputs": [
        {
          "name": "howMany_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "amtValReturned",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "burnReturns",
      "inputs": [
        {
          "name": "amt_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "rv",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "burnTo",
      "inputs": [
        {
          "name": "howMany_",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "to_",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "amount",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "crosschainBurn",
      "inputs": [
        {
          "name": "_from",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "_amount",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "crosschainMint",
      "inputs": [
        {
          "name": "_to",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "_amount",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "currentPrice",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "decimals",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint8",
          "internalType": "uint8"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "deconstructBurn",
      "inputs": [
        {
          "name": "amountToBurn_",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "tokensToRedeem",
          "type": "address[]",
          "internalType": "address[]"
        }
      ],
      "outputs": [
        {
          "name": "shareBurned",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "lastBlockSupply",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "lastPrice",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "lastPriceBlock",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "mint",
      "inputs": [
        {
          "name": "howMany_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [],
      "stateMutability": "payable"
    },
    {
      "type": "function",
      "name": "mintCost",
      "inputs": [
        {
          "name": "amt_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "mintFromETH",
      "inputs": [],
      "outputs": [
        {
          "name": "howMuchMinted",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "payable"
    },
    {
      "type": "function",
      "name": "name",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "string",
          "internalType": "string"
        }
      ],
      "stateMutability": "pure"
    },
    {
      "type": "function",
      "name": "nonces",
      "inputs": [
        {
          "name": "owner",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "result",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "permit",
      "inputs": [
        {
          "name": "owner",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "spender",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "value",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "deadline",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "v",
          "type": "uint8",
          "internalType": "uint8"
        },
        {
          "name": "r",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "s",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "supportsInterface",
      "inputs": [
        {
          "name": "_interfaceId",
          "type": "bytes4",
          "internalType": "bytes4"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "symbol",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "string",
          "internalType": "string"
        }
      ],
      "stateMutability": "pure"
    },
    {
      "type": "function",
      "name": "totalSupply",
      "inputs": [],
      "outputs": [
        {
          "name": "result",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "transfer",
      "inputs": [
        {
          "name": "to",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "amount",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "transferFrom",
      "inputs": [
        {
          "name": "from",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "to",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "amount",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "version",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "string",
          "internalType": "string"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "event",
      "name": "Approval",
      "inputs": [
        {
          "name": "owner",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "spender",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "amount",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "CrosschainBurn",
      "inputs": [
        {
          "name": "from",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "amount",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "sender",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "CrosschainMint",
      "inputs": [
        {
          "name": "to",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "amount",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "sender",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "PriceUpdated",
      "inputs": [
        {
          "name": "newPrice",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "Transfer",
      "inputs": [
        {
          "name": "from",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "to",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "amount",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "WillBurned",
      "inputs": [
        {
          "name": "from",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "amount",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "ethReturned",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "WillDeconstructBurned",
      "inputs": [
        {
          "name": "from",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "willAmount",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "ethAmount",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "WillMinted",
      "inputs": [
        {
          "name": "to",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "amount",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "ethValue",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "error",
      "name": "AllowanceOverflow",
      "inputs": []
    },
    {
      "type": "error",
      "name": "AllowanceUnderflow",
      "inputs": []
    },
    {
      "type": "error",
      "name": "BurnRefundF",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InsufficentBalance",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InsufficientAllowance",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InsufficientBalance",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InsufficientValue",
      "inputs": [
        {
          "name": "required",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "provided",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "InvalidPermit",
      "inputs": []
    },
    {
      "type": "error",
      "name": "PayCallF",
      "inputs": []
    },
    {
      "type": "error",
      "name": "Permit2AllowanceIsFixedAtInfinity",
      "inputs": []
    },
    {
      "type": "error",
      "name": "PermitExpired",
      "inputs": []
    },
    {
      "type": "error",
      "name": "Reentrant",
      "inputs": []
    },
    {
      "type": "error",
      "name": "TotalSupplyOverflow",
      "inputs": []
    },
    {
      "type": "error",
      "name": "TransferFailedFor",
      "inputs": [
        {
          "name": "failingToken",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "Unauthorized",
      "inputs": []
    },
    {
      "type": "error",
      "name": "ValueMismatch",
      "inputs": []
    }
  ],
  "Membranes": [
    {
      "type": "function",
      "name": "createMembrane",
      "inputs": [
        {
          "name": "tokens_",
          "type": "address[]",
          "internalType": "address[]"
        },
        {
          "name": "balances_",
          "type": "uint256[]",
          "internalType": "uint256[]"
        },
        {
          "name": "meta_",
          "type": "string",
          "internalType": "string"
        }
      ],
      "outputs": [
        {
          "name": "id",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "gCheck",
      "inputs": [
        {
          "name": "who_",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "membraneID_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "s",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "getMembraneById",
      "inputs": [
        {
          "name": "id_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "tuple",
          "internalType": "struct Membrane",
          "components": [
            {
              "name": "tokens",
              "type": "address[]",
              "internalType": "address[]"
            },
            {
              "name": "balances",
              "type": "uint256[]",
              "internalType": "uint256[]"
            },
            {
              "name": "meta",
              "type": "string",
              "internalType": "string"
            },
            {
              "name": "createdAt",
              "type": "uint256",
              "internalType": "uint256"
            }
          ]
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "integrityCheck",
      "inputs": [
        {
          "name": "nodeId",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "s",
          "type": "bool",
          "internalType": "bool"
        },
        {
          "name": "i",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "setInitWillWe",
      "inputs": [],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "willWe",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "contract IFun"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "event",
      "name": "MembraneCreated",
      "inputs": [
        {
          "name": "creator",
          "type": "address",
          "indexed": false,
          "internalType": "address"
        },
        {
          "name": "membraneId",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "CID",
          "type": "string",
          "indexed": false,
          "internalType": "string"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "WillWeSet",
      "inputs": [
        {
          "name": "willWeAddress",
          "type": "address",
          "indexed": false,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "error",
      "name": "Membrane__EmptyFieldOnMembraneCreation",
      "inputs": []
    },
    {
      "type": "error",
      "name": "Membrane__UnauthorizedWillWeSet",
      "inputs": []
    },
    {
      "type": "error",
      "name": "membraneNotFound",
      "inputs": []
    }
  ],
  "Execution": [
    {
      "type": "constructor",
      "inputs": [
        {
          "name": "WillToken_",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "fallback",
      "stateMutability": "payable"
    },
    {
      "type": "receive",
      "stateMutability": "payable"
    },
    {
      "type": "function",
      "name": "DOMAIN_SEPARATOR",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "EIP712_DOMAIN_TYPEHASH",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "MOVEMENT_TYPEHASH",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "WillToken",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "WillWe",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "contract IFun"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "createEndpointForOwner",
      "inputs": [
        {
          "name": "origin",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "nodeId",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "owner",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "endpoint",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "createInitWillWeEndpoint",
      "inputs": [
        {
          "name": "nodeId_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "endpoint",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "endpointOwner",
      "inputs": [
        {
          "name": "endpointAddress",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "executeQueue",
      "inputs": [
        {
          "name": "queueHash",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [
        {
          "name": "success",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "getDigestToSign",
      "inputs": [
        {
          "name": "movement",
          "type": "tuple",
          "internalType": "struct Movement",
          "components": [
            {
              "name": "category",
              "type": "uint8",
              "internalType": "enum MovementType"
            },
            {
              "name": "initiatior",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "exeAccount",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "viaNode",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "expiresAt",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "description",
              "type": "string",
              "internalType": "string"
            },
            {
              "name": "executedPayload",
              "type": "bytes",
              "internalType": "bytes"
            }
          ]
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "getEIP712MessageHash",
      "inputs": [
        {
          "name": "movementHash",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "getLatentMovements",
      "inputs": [
        {
          "name": "nodeId",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "latentMovements",
          "type": "tuple[]",
          "internalType": "struct LatentMovement[]",
          "components": [
            {
              "name": "movement",
              "type": "tuple",
              "internalType": "struct Movement",
              "components": [
                {
                  "name": "category",
                  "type": "uint8",
                  "internalType": "enum MovementType"
                },
                {
                  "name": "initiatior",
                  "type": "address",
                  "internalType": "address"
                },
                {
                  "name": "exeAccount",
                  "type": "address",
                  "internalType": "address"
                },
                {
                  "name": "viaNode",
                  "type": "uint256",
                  "internalType": "uint256"
                },
                {
                  "name": "expiresAt",
                  "type": "uint256",
                  "internalType": "uint256"
                },
                {
                  "name": "description",
                  "type": "string",
                  "internalType": "string"
                },
                {
                  "name": "executedPayload",
                  "type": "bytes",
                  "internalType": "bytes"
                }
              ]
            },
            {
              "name": "signatureQueue",
              "type": "tuple",
              "internalType": "struct SignatureQueue",
              "components": [
                {
                  "name": "state",
                  "type": "uint8",
                  "internalType": "enum SQState"
                },
                {
                  "name": "Action",
                  "type": "tuple",
                  "internalType": "struct Movement",
                  "components": [
                    {
                      "name": "category",
                      "type": "uint8",
                      "internalType": "enum MovementType"
                    },
                    {
                      "name": "initiatior",
                      "type": "address",
                      "internalType": "address"
                    },
                    {
                      "name": "exeAccount",
                      "type": "address",
                      "internalType": "address"
                    },
                    {
                      "name": "viaNode",
                      "type": "uint256",
                      "internalType": "uint256"
                    },
                    {
                      "name": "expiresAt",
                      "type": "uint256",
                      "internalType": "uint256"
                    },
                    {
                      "name": "description",
                      "type": "string",
                      "internalType": "string"
                    },
                    {
                      "name": "executedPayload",
                      "type": "bytes",
                      "internalType": "bytes"
                    }
                  ]
                },
                {
                  "name": "Signers",
                  "type": "address[]",
                  "internalType": "address[]"
                },
                {
                  "name": "Sigs",
                  "type": "bytes[]",
                  "internalType": "bytes[]"
                }
              ]
            },
            {
              "name": "movementHash",
              "type": "bytes32",
              "internalType": "bytes32"
            }
          ]
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "getSigQueue",
      "inputs": [
        {
          "name": "hash_",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "tuple",
          "internalType": "struct SignatureQueue",
          "components": [
            {
              "name": "state",
              "type": "uint8",
              "internalType": "enum SQState"
            },
            {
              "name": "Action",
              "type": "tuple",
              "internalType": "struct Movement",
              "components": [
                {
                  "name": "category",
                  "type": "uint8",
                  "internalType": "enum MovementType"
                },
                {
                  "name": "initiatior",
                  "type": "address",
                  "internalType": "address"
                },
                {
                  "name": "exeAccount",
                  "type": "address",
                  "internalType": "address"
                },
                {
                  "name": "viaNode",
                  "type": "uint256",
                  "internalType": "uint256"
                },
                {
                  "name": "expiresAt",
                  "type": "uint256",
                  "internalType": "uint256"
                },
                {
                  "name": "description",
                  "type": "string",
                  "internalType": "string"
                },
                {
                  "name": "executedPayload",
                  "type": "bytes",
                  "internalType": "bytes"
                }
              ]
            },
            {
              "name": "Signers",
              "type": "address[]",
              "internalType": "address[]"
            },
            {
              "name": "Sigs",
              "type": "bytes[]",
              "internalType": "bytes[]"
            }
          ]
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "hashMovement",
      "inputs": [
        {
          "name": "movement",
          "type": "tuple",
          "internalType": "struct Movement",
          "components": [
            {
              "name": "category",
              "type": "uint8",
              "internalType": "enum MovementType"
            },
            {
              "name": "initiatior",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "exeAccount",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "viaNode",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "expiresAt",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "description",
              "type": "string",
              "internalType": "string"
            },
            {
              "name": "executedPayload",
              "type": "bytes",
              "internalType": "bytes"
            }
          ]
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "pure"
    },
    {
      "type": "function",
      "name": "isQueueValid",
      "inputs": [
        {
          "name": "sigHash",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "isValidSignature",
      "inputs": [
        {
          "name": "_hash",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "_signature",
          "type": "bytes",
          "internalType": "bytes"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bytes4",
          "internalType": "bytes4"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "lastSalt",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "nextSalt",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "removeLatentAction",
      "inputs": [
        {
          "name": "actionHash",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "index",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "removeSignature",
      "inputs": [
        {
          "name": "queueHash",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "index",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "signer",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "setWillWe",
      "inputs": [
        {
          "name": "implementation",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "startMovement",
      "inputs": [
        {
          "name": "typeOfMovement",
          "type": "uint8",
          "internalType": "uint8"
        },
        {
          "name": "nodeId",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "expiresInDays",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "executingAccount",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "description",
          "type": "string",
          "internalType": "string"
        },
        {
          "name": "data",
          "type": "bytes",
          "internalType": "bytes"
        }
      ],
      "outputs": [
        {
          "name": "movementHash",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "submitSignatures",
      "inputs": [
        {
          "name": "queueHash",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "signers",
          "type": "address[]",
          "internalType": "address[]"
        },
        {
          "name": "signatures",
          "type": "bytes[]",
          "internalType": "bytes[]"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "event",
      "name": "LatentActionRemoved",
      "inputs": [
        {
          "name": "nodeId",
          "type": "uint256",
          "indexed": true,
          "internalType": "uint256"
        },
        {
          "name": "actionHash",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        },
        {
          "name": "index",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "NewMovementCreated",
      "inputs": [
        {
          "name": "nodeId",
          "type": "uint256",
          "indexed": true,
          "internalType": "uint256"
        },
        {
          "name": "initiator",
          "type": "address",
          "indexed": false,
          "internalType": "address"
        },
        {
          "name": "movementHash",
          "type": "bytes32",
          "indexed": false,
          "internalType": "bytes32"
        },
        {
          "name": "description",
          "type": "string",
          "indexed": false,
          "internalType": "string"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "NewSignaturesSubmitted",
      "inputs": [
        {
          "name": "queueHash",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "QueueExecuted",
      "inputs": [
        {
          "name": "nodeId",
          "type": "uint256",
          "indexed": true,
          "internalType": "uint256"
        },
        {
          "name": "queueHash",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "SignatureRemoved",
      "inputs": [
        {
          "name": "nodeId",
          "type": "uint256",
          "indexed": true,
          "internalType": "uint256"
        },
        {
          "name": "queueHash",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        },
        {
          "name": "signer",
          "type": "address",
          "indexed": false,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "WillWeSet",
      "inputs": [
        {
          "name": "implementation",
          "type": "address",
          "indexed": false,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "error",
      "name": "EXE_A0sig",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_ActionIndexMismatch",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_AlreadyHasEndpoint",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_AlreadyInit",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_AlreadyInitialized",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_AlreadySigned",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_BadOwnerOrAuthType",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_EmptyUnallowed",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_ExpiredMovement",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_ExpiredQueue",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_InProgress",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_InvalidQueue",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_LenErr",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_NoDescription",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_NoMembersForNode",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_NoMovementType",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_NoSignatures",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_NoType",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_NotExeAccOwner",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_NotNodeMember",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_OnlyMore",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_OnlySigner",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_OnlyWillWe",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_SQInvalid",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_UnavailableState",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_UninitQueue",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_ZeroLen",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EXE_exeQFail",
      "inputs": []
    }
  ],
  "WillWe": [
    {
      "type": "constructor",
      "inputs": [
        {
          "name": "Execution",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "Membrane",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "Will",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "allMembersOf",
      "inputs": [
        {
          "name": "fid_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "address[]",
          "internalType": "address[]"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "asRootValuation",
      "inputs": [
        {
          "name": "target_",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "amount",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "balanceOf",
      "inputs": [
        {
          "name": "owner",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "id",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "result",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "balanceOfBatch",
      "inputs": [
        {
          "name": "owners",
          "type": "address[]",
          "internalType": "address[]"
        },
        {
          "name": "ids",
          "type": "uint256[]",
          "internalType": "uint256[]"
        }
      ],
      "outputs": [
        {
          "name": "balances",
          "type": "uint256[]",
          "internalType": "uint256[]"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "burn",
      "inputs": [
        {
          "name": "fid_",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "amount_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "topVal",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "burnPath",
      "inputs": [
        {
          "name": "target_",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "amount",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "calculateUserTargetedPreferenceAmount",
      "inputs": [
        {
          "name": "childId",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "parentId",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "signal",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "user",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "control",
      "inputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "createEndpointForOwner",
      "inputs": [
        {
          "name": "nodeId_",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "owner",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "endpointAddress",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "executionAddress",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "getAllNodesForRoot",
      "inputs": [
        {
          "name": "rootAddress",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "userIfAny",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "nodes",
          "type": "tuple[]",
          "internalType": "struct NodeState[]",
          "components": [
            {
              "name": "basicInfo",
              "type": "string[12]",
              "internalType": "string[12]"
            },
            {
              "name": "membraneMeta",
              "type": "string",
              "internalType": "string"
            },
            {
              "name": "membersOfNode",
              "type": "address[]",
              "internalType": "address[]"
            },
            {
              "name": "childrenNodes",
              "type": "string[]",
              "internalType": "string[]"
            },
            {
              "name": "movementEndpoints",
              "type": "address[]",
              "internalType": "address[]"
            },
            {
              "name": "rootPath",
              "type": "string[]",
              "internalType": "string[]"
            },
            {
              "name": "signals",
              "type": "uint256[]",
              "internalType": "uint256[]"
            }
          ]
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "getChangePrevalence",
      "inputs": [
        {
          "name": "nodeId_",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "signal_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "getChildrenOf",
      "inputs": [
        {
          "name": "fid_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "uint256[]",
          "internalType": "uint256[]"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "getFidPath",
      "inputs": [
        {
          "name": "fid_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "fids",
          "type": "uint256[]",
          "internalType": "uint256[]"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "getMembraneOf",
      "inputs": [
        {
          "name": "fid_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "getNodeData",
      "inputs": [
        {
          "name": "nodeId",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "user",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "nodeData",
          "type": "tuple",
          "internalType": "struct NodeState",
          "components": [
            {
              "name": "basicInfo",
              "type": "string[12]",
              "internalType": "string[12]"
            },
            {
              "name": "membraneMeta",
              "type": "string",
              "internalType": "string"
            },
            {
              "name": "membersOfNode",
              "type": "address[]",
              "internalType": "address[]"
            },
            {
              "name": "childrenNodes",
              "type": "string[]",
              "internalType": "string[]"
            },
            {
              "name": "movementEndpoints",
              "type": "address[]",
              "internalType": "address[]"
            },
            {
              "name": "rootPath",
              "type": "string[]",
              "internalType": "string[]"
            },
            {
              "name": "signals",
              "type": "uint256[]",
              "internalType": "uint256[]"
            }
          ]
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "getNodes",
      "inputs": [
        {
          "name": "nodeIds",
          "type": "uint256[]",
          "internalType": "uint256[]"
        }
      ],
      "outputs": [
        {
          "name": "nodes",
          "type": "tuple[]",
          "internalType": "struct NodeState[]",
          "components": [
            {
              "name": "basicInfo",
              "type": "string[12]",
              "internalType": "string[12]"
            },
            {
              "name": "membraneMeta",
              "type": "string",
              "internalType": "string"
            },
            {
              "name": "membersOfNode",
              "type": "address[]",
              "internalType": "address[]"
            },
            {
              "name": "childrenNodes",
              "type": "string[]",
              "internalType": "string[]"
            },
            {
              "name": "movementEndpoints",
              "type": "address[]",
              "internalType": "address[]"
            },
            {
              "name": "rootPath",
              "type": "string[]",
              "internalType": "string[]"
            },
            {
              "name": "signals",
              "type": "uint256[]",
              "internalType": "uint256[]"
            }
          ]
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "getParentOf",
      "inputs": [
        {
          "name": "fid_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "getUserNodeSignals",
      "inputs": [
        {
          "name": "user_",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "node_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "uint256[]",
          "internalType": "uint256[]"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "inParentDenomination",
      "inputs": [
        {
          "name": "amt_",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "id_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "inParentVal",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "inflationOf",
      "inputs": [
        {
          "name": "nodeId",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "initSelfControl",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "isApprovedForAll",
      "inputs": [
        {
          "name": "owner",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "operator",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "result",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "isMember",
      "inputs": [
        {
          "name": "whoabout_",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "whereabout_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "localizeEndpoint",
      "inputs": [
        {
          "name": "endpoint_",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "endpointParent_",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "owner_",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "membershipEnforce",
      "inputs": [
        {
          "name": "target",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "fid_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "s",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "membershipID",
      "inputs": [
        {
          "name": "fid_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "pure"
    },
    {
      "type": "function",
      "name": "mint",
      "inputs": [
        {
          "name": "fid_",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "amount_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "mintInflation",
      "inputs": [
        {
          "name": "node",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "amount",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "mintMembership",
      "inputs": [
        {
          "name": "fid_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "mintPath",
      "inputs": [
        {
          "name": "target_",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "amount_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "name",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "string",
          "internalType": "string"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "options",
      "inputs": [
        {
          "name": "NodeXUserXValue",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "valueAtTime",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "redistribute",
      "inputs": [
        {
          "name": "nodeId_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "distributedAmt",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "redistributePath",
      "inputs": [
        {
          "name": "nodeId_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "distributedAmt",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "resignal",
      "inputs": [
        {
          "name": "targetNode_",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "originator",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "safeBatchTransferFrom",
      "inputs": [
        {
          "name": "from",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "to",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "ids",
          "type": "uint256[]",
          "internalType": "uint256[]"
        },
        {
          "name": "amounts",
          "type": "uint256[]",
          "internalType": "uint256[]"
        },
        {
          "name": "data",
          "type": "bytes",
          "internalType": "bytes"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "safeTransferFrom",
      "inputs": [
        {
          "name": "from",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "to",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "id",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "amount",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "data",
          "type": "bytes",
          "internalType": "bytes"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "sendSignal",
      "inputs": [
        {
          "name": "targetNode_",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "signals",
          "type": "uint256[]",
          "internalType": "uint256[]"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "setApprovalForAll",
      "inputs": [
        {
          "name": "operator",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "isApproved",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "setControl",
      "inputs": [
        {
          "name": "newController",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "spawnNode",
      "inputs": [
        {
          "name": "fid_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "newID",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "spawnNodeWithMembrane",
      "inputs": [
        {
          "name": "fid_",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "tokens_",
          "type": "address[]",
          "internalType": "address[]"
        },
        {
          "name": "balances_",
          "type": "uint256[]",
          "internalType": "uint256[]"
        },
        {
          "name": "meta_",
          "type": "string",
          "internalType": "string"
        },
        {
          "name": "inflationRate_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "newID",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "spawnRootNode",
      "inputs": [
        {
          "name": "fungible20_",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "fID",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "supportsInterface",
      "inputs": [
        {
          "name": "interfaceId",
          "type": "bytes4",
          "internalType": "bytes4"
        }
      ],
      "outputs": [
        {
          "name": "result",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "symbol",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "string",
          "internalType": "string"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "taxPolicyPreference",
      "inputs": [
        {
          "name": "rootToken_",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "taxRate_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "toAddress",
      "inputs": [
        {
          "name": "x",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "pure"
    },
    {
      "type": "function",
      "name": "toID",
      "inputs": [
        {
          "name": "x",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "pure"
    },
    {
      "type": "function",
      "name": "totalSupply",
      "inputs": [
        {
          "name": "nodeId",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "uri",
      "inputs": [
        {
          "name": "id_",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "string",
          "internalType": "string"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "event",
      "name": "ApprovalForAll",
      "inputs": [
        {
          "name": "owner",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "operator",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "isApproved",
          "type": "bool",
          "indexed": false,
          "internalType": "bool"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "Burned",
      "inputs": [
        {
          "name": "fromAddressOrNode",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "nodeId",
          "type": "uint256",
          "indexed": true,
          "internalType": "uint256"
        },
        {
          "name": "amount",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "CreatedEndpoint",
      "inputs": [
        {
          "name": "endpoint",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "owner",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "nodeId",
          "type": "uint256",
          "indexed": true,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "InflationRateChanged",
      "inputs": [
        {
          "name": "nodeId",
          "type": "uint256",
          "indexed": true,
          "internalType": "uint256"
        },
        {
          "name": "oldInflationRate",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "newInflationRate",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "InflationSignal",
      "inputs": [
        {
          "name": "nodeId",
          "type": "uint256",
          "indexed": true,
          "internalType": "uint256"
        },
        {
          "name": "origin",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "inflationRate",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "MemberRemoved",
      "inputs": [
        {
          "name": "userAddress",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "nodeId",
          "type": "uint256",
          "indexed": true,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "MembershipMinted",
      "inputs": [
        {
          "name": "who",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "nodeId",
          "type": "uint256",
          "indexed": true,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "MembraneChanged",
      "inputs": [
        {
          "name": "nodeId",
          "type": "uint256",
          "indexed": true,
          "internalType": "uint256"
        },
        {
          "name": "previousMembrane",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "newMembrane",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "MembraneSignal",
      "inputs": [
        {
          "name": "nodeId",
          "type": "uint256",
          "indexed": true,
          "internalType": "uint256"
        },
        {
          "name": "origin",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "membraneId",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "Minted",
      "inputs": [
        {
          "name": "fromAddressOrNode",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "nodeId",
          "type": "uint256",
          "indexed": true,
          "internalType": "uint256"
        },
        {
          "name": "amount",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "NewNode",
      "inputs": [
        {
          "name": "newId",
          "type": "uint256",
          "indexed": true,
          "internalType": "uint256"
        },
        {
          "name": "parentId",
          "type": "uint256",
          "indexed": true,
          "internalType": "uint256"
        },
        {
          "name": "creator",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "NewRootNode",
      "inputs": [
        {
          "name": "rootNodeId",
          "type": "uint256",
          "indexed": true,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "Resignaled",
      "inputs": [
        {
          "name": "sender",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "nodeId",
          "type": "uint256",
          "indexed": true,
          "internalType": "uint256"
        },
        {
          "name": "origin",
          "type": "address",
          "indexed": false,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "SelfControlAtAddress",
      "inputs": [
        {
          "name": "AgencyLocus",
          "type": "address",
          "indexed": false,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "SharesGenerated",
      "inputs": [
        {
          "name": "nodeId",
          "type": "uint256",
          "indexed": true,
          "internalType": "uint256"
        },
        {
          "name": "amount",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "TransferBatch",
      "inputs": [
        {
          "name": "operator",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "from",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "to",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "ids",
          "type": "uint256[]",
          "indexed": false,
          "internalType": "uint256[]"
        },
        {
          "name": "amounts",
          "type": "uint256[]",
          "indexed": false,
          "internalType": "uint256[]"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "TransferSingle",
      "inputs": [
        {
          "name": "operator",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "from",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "to",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "id",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "amount",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "URI",
      "inputs": [
        {
          "name": "value",
          "type": "string",
          "indexed": false,
          "internalType": "string"
        },
        {
          "name": "id",
          "type": "uint256",
          "indexed": true,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "UserNodeSignal",
      "inputs": [
        {
          "name": "nodeId",
          "type": "uint256",
          "indexed": true,
          "internalType": "uint256"
        },
        {
          "name": "user",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "signals",
          "type": "uint256[]",
          "indexed": false,
          "internalType": "uint256[]"
        }
      ],
      "anonymous": false
    },
    {
      "type": "error",
      "name": "AccountBalanceOverflow",
      "inputs": []
    },
    {
      "type": "error",
      "name": "AlreadyMember",
      "inputs": []
    },
    {
      "type": "error",
      "name": "ArrayLengthsMismatch",
      "inputs": []
    },
    {
      "type": "error",
      "name": "BadLen",
      "inputs": []
    },
    {
      "type": "error",
      "name": "BaseOrNonFungible",
      "inputs": []
    },
    {
      "type": "error",
      "name": "BurnE20TransferFailed",
      "inputs": []
    },
    {
      "type": "error",
      "name": "CannotSkip",
      "inputs": []
    },
    {
      "type": "error",
      "name": "Disabled",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EOA",
      "inputs": []
    },
    {
      "type": "error",
      "name": "Endpoint",
      "inputs": []
    },
    {
      "type": "error",
      "name": "ExecutionOnly",
      "inputs": []
    },
    {
      "type": "error",
      "name": "IncompleteSign",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InsufficientAmt",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InsufficientBalance",
      "inputs": []
    },
    {
      "type": "error",
      "name": "MembershipOp",
      "inputs": []
    },
    {
      "type": "error",
      "name": "MembraneNotFound",
      "inputs": []
    },
    {
      "type": "error",
      "name": "MintE20TransferFailed",
      "inputs": []
    },
    {
      "type": "error",
      "name": "No",
      "inputs": []
    },
    {
      "type": "error",
      "name": "NoControl",
      "inputs": []
    },
    {
      "type": "error",
      "name": "NoSoup",
      "inputs": []
    },
    {
      "type": "error",
      "name": "NoTimeDelta",
      "inputs": []
    },
    {
      "type": "error",
      "name": "NodeAlreadyExists",
      "inputs": []
    },
    {
      "type": "error",
      "name": "NodeNotFound",
      "inputs": []
    },
    {
      "type": "error",
      "name": "Noise",
      "inputs": []
    },
    {
      "type": "error",
      "name": "NoiseNotVoice",
      "inputs": []
    },
    {
      "type": "error",
      "name": "NotMember",
      "inputs": []
    },
    {
      "type": "error",
      "name": "NotNodeMember",
      "inputs": []
    },
    {
      "type": "error",
      "name": "NotOwnerNorApproved",
      "inputs": []
    },
    {
      "type": "error",
      "name": "Overreach",
      "inputs": []
    },
    {
      "type": "error",
      "name": "ResignalMismatch",
      "inputs": []
    },
    {
      "type": "error",
      "name": "RootExists",
      "inputs": []
    },
    {
      "type": "error",
      "name": "SignalOverflow",
      "inputs": []
    },
    {
      "type": "error",
      "name": "TargetIsRoot",
      "inputs": []
    },
    {
      "type": "error",
      "name": "TransferToNonERC1155ReceiverImplementer",
      "inputs": []
    },
    {
      "type": "error",
      "name": "TransferToZeroAddress",
      "inputs": []
    },
    {
      "type": "error",
      "name": "Unautorised",
      "inputs": []
    },
    {
      "type": "error",
      "name": "Unqualified",
      "inputs": []
    },
    {
      "type": "error",
      "name": "UnregisteredFungible",
      "inputs": []
    },
    {
      "type": "error",
      "name": "UnsoundMembership",
      "inputs": []
    },
    {
      "type": "error",
      "name": "UnsupportedTransfer",
      "inputs": []
    },
    {
      "type": "error",
      "name": "isControled",
      "inputs": []
    }
  ],
  "IERC20": [
    {
      "constant": true,
      "inputs": [],
      "name": "name",
      "outputs": [
        {
          "name": "",
          "type": "string"
        }
      ],
      "payable": false,
      "stateMutability": "view",
      "type": "function"
    },
    {
      "constant": false,
      "inputs": [
        {
          "name": "_spender",
          "type": "address"
        },
        {
          "name": "_value",
          "type": "uint256"
        }
      ],
      "name": "approve",
      "outputs": [
        {
          "name": "",
          "type": "bool"
        }
      ],
      "payable": false,
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "constant": true,
      "inputs": [],
      "name": "totalSupply",
      "outputs": [
        {
          "name": "",
          "type": "uint256"
        }
      ],
      "payable": false,
      "stateMutability": "view",
      "type": "function"
    },
    {
      "constant": false,
      "inputs": [
        {
          "name": "_from",
          "type": "address"
        },
        {
          "name": "_to",
          "type": "address"
        },
        {
          "name": "_value",
          "type": "uint256"
        }
      ],
      "name": "transferFrom",
      "outputs": [
        {
          "name": "",
          "type": "bool"
        }
      ],
      "payable": false,
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "constant": true,
      "inputs": [],
      "name": "decimals",
      "outputs": [
        {
          "name": "",
          "type": "uint8"
        }
      ],
      "payable": false,
      "stateMutability": "view",
      "type": "function"
    },
    {
      "constant": true,
      "inputs": [
        {
          "name": "_owner",
          "type": "address"
        }
      ],
      "name": "balanceOf",
      "outputs": [
        {
          "name": "balance",
          "type": "uint256"
        }
      ],
      "payable": false,
      "stateMutability": "view",
      "type": "function"
    },
    {
      "constant": true,
      "inputs": [],
      "name": "symbol",
      "outputs": [
        {
          "name": "",
          "type": "string"
        }
      ],
      "payable": false,
      "stateMutability": "view",
      "type": "function"
    },
    {
      "constant": false,
      "inputs": [
        {
          "name": "_to",
          "type": "address"
        },
        {
          "name": "_value",
          "type": "uint256"
        }
      ],
      "name": "transfer",
      "outputs": [
        {
          "name": "",
          "type": "bool"
        }
      ],
      "payable": false,
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "constant": true,
      "inputs": [
        {
          "name": "_owner",
          "type": "address"
        },
        {
          "name": "_spender",
          "type": "address"
        }
      ],
      "name": "allowance",
      "outputs": [
        {
          "name": "",
          "type": "uint256"
        }
      ],
      "payable": false,
      "stateMutability": "view",
      "type": "function"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "owner",
          "type": "address"
        },
        {
          "indexed": true,
          "name": "spender",
          "type": "address"
        },
        {
          "indexed": false,
          "name": "value",
          "type": "uint256"
        }
      ],
      "name": "Approval",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "from",
          "type": "address"
        },
        {
          "indexed": true,
          "name": "to",
          "type": "address"
        },
        {
          "indexed": false,
          "name": "value",
          "type": "uint256"
        }
      ],
      "name": "Transfer",
      "type": "event"
    }
  ]
};
